# Generated by Django 2.1.7 on 2019-05-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_auto_20190211_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='explorer.CollectionType'),
        ),
        migrations.AlterField(
            model_name='collectiontype',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='explorer.Service'),
        ),
        migrations.AlterField(
            model_name='comparisongroup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='explorer.Service'),
        ),
        migrations.AlterField(
            model_name='comparisonlabel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='explorer.ComparisonSuperSet'),
        ),
        migrations.AlterField(
            model_name='comparisonset',
            name='collectiontype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='explorer.CollectionType'),
        ),
        migrations.AlterField(
            model_name='comparisonset',
            name='superset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='explorer.ComparisonSuperSet'),
        ),
        migrations.AlterField(
            model_name='comparisonsuperset',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comparisonsuperset',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='explorer.ComparisonGroup'),
        ),
        migrations.AlterField(
            model_name='comparisonunit',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='explorer.CollectionItem'),
        ),
        migrations.AlterField(
            model_name='comparisonunit',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='explorer.ComparisonSet'),
        ),
        migrations.AlterField(
            model_name='service',
            name='collective_name',
            field=models.CharField(default='Reports', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcollectionitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='explorer.CollectionItem'),
        ),
    ]
