# Generated by Django 2.2.1 on 2019-10-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0028_auto_20190807_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisongroup',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='explorer.Service'),
        ),
        migrations.AlterField(
            model_name='comparisonlabel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='explorer.ComparisonSuperSet'),
        ),
        migrations.AlterField(
            model_name='comparisonset',
            name='superset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='explorer.ComparisonSuperSet'),
        ),
    ]
